### ISSUE TITLE
Assignment

### ISSUE THREAD

**Issue by nginx500** [java-basics-1007/java-hello#2]
1. How to check java version?
2. With notepad++ Create a class named as Solution. Define a main method inside it and print "welcome". Compile and run it.
3. Using Intellij: Create a class Student. with field as int id. Define a class BlueprintStudentMain and its main method. Create object for Student and initialize id field only. Print the id field of the object.

**Comment by nginx500** [comment]
@avnishhero7 finish this assignment before next class.

**Comment by avnishhero7** [comment]
1.) java -version
2.) Done
![Solution - Welcome HW](https://github.com/java-basics-1007/java-hello/assets/173557447/de44bb06-85a3-43bd-808b-f4b2e30cd713)
3.) Done
